export const IMGS = {
  heroBg:       "/images/hero_bg.jpg",
  featureMain:  "/images/feature_main.jpg",
  featureLeft:  "/images/feature_left.jpg",
  featureRight: "/images/feature_right.jpg",
  screen1:      "/images/screen1.jpg",
  screen2:      "/images/screen2.jpg",
  screen3:      "/images/screen3.jpg",
  screen4:      "/images/screen4.jpg",
  screen5:      "/images/screen5.jpg",
  screen6:      "/images/screen6.jpg",
  screen7:      "/images/screen7.jpg",
  screen8:      "/images/screen8.jpg",
  team1:        "/images/team1.jpg",
  team2:        "/images/team2.jpg",
  team3:        "/images/team3.jpg",
  ctaBg:        "/images/cta_bg.jpg",
};
